### PR TITLE
Sand maker

### PR DESCRIPTION
**Pull request by mitchellblom**
@blairvansant The JS is ready for your review. Next steps would be:
- make "No Meat" checkbox reset the other meats.
- additional styling

### CODE REVIEW

**Comment by mitchellblom** [comment]
And lines 15 and 16 on SandwichMaker.js need to be removed from there and integrated into the DOMhandler.

**Comment by blairvansant** [comment]
I'm going to try to look at these tonight after work, but no promises. I'm zonked!😴

**Comment by mitchellblom** [comment]
We can always go over it together in the morning. No worries dude!

**Comment by blairvansant** [comment]
-removing meats after "no meats" is selected
-aligning label and input

other than that 👍 

I will mess around after work

**Comment by mitchellblom** [comment]
thanks man!

**Comment by blairvansant** [comment]
👍

**Comment by mitchellblom** [comment]
Thanks!

**Pull request merged**
